import pandas as pd
import matplotlib.pyplot as plt
import requests
import os

# Telegram Bot Token and Chat ID (these could be set as environment variables or in a config file)
bot_token = '7751308203:AAF_5lHsCIfb5Uo2ZM6FVHcnyofJKm1jwdA'
chat_id = '-4647316485'

# File path (Excel file generated by scraping script)
file_path = 'daily_price_multiple_hotels.xlsx'
image_path = 'hotel_prices.png'

# Telegram API URL to send messages
url = f"https://api.telegram.org/bot{bot_token}/sendPhoto"

def read_excel_and_create_image(file_path, image_path):
    try:
        # Read the Excel file
        df = pd.read_excel(file_path)

        # Create a plot of the data
        plt.figure(figsize=(14, 10))  # Adjust the figure size to make the table larger
        plt.axis('off')  # Hide axes

        # Customize the table appearance
        table = plt.table(
            cellText=df.values, 
            colLabels=df.columns, 
            loc='center', 
            cellLoc='center', 
            colColours=['#f2f2f2']*len(df.columns)
        )

        # Set font size for table text
        table.auto_set_font_size(False)
        table.set_fontsize(14)  # Adjust the font size to make the text bigger

        # Adjust the column width (optional)
        table.auto_set_column_width(col=list(range(len(df.columns))))  # Automatically adjust column widths

        # Save the table as a PNG image with high resolution (DPI)
        plt.savefig(image_path, format='png', bbox_inches='tight', pad_inches=0.1, dpi=300)  # Increase DPI for better resolution
        plt.close()

        print(f"Image saved as {image_path}")
    except Exception as e:
        print(f"Error creating PNG image: {e}")

def send_telegram_image(image_path):
    try:
        # Open the PNG image in binary mode
        with open(image_path, 'rb') as file:
            # Send the image via Telegram
            response = requests.post(url, data={'chat_id': chat_id}, files={'photo': file})
        
        # Check if the message was sent successfully
        if response.status_code == 200:
            print("Image sent successfully to Telegram!")
        else:
            print(f"Failed to send image. Status code: {response.status_code}, Response: {response.text}")
    except Exception as e:
        print(f"Error sending image to Telegram: {e}")

if __name__ == "__main__":
    # Ensure the file exists
    if os.path.exists(file_path):
        # Create the PNG image from the Excel data
        read_excel_and_create_image(file_path, image_path)

        # Ensure the image was created successfully
        if os.path.exists(image_path):
            # Send the image via Telegram
            send_telegram_image(image_path)
        else:
            print(f"Image creation failed: {image_path} not found!")
    else:
        print(f"Excel file {file_path} not found!")
