name: Hotel Price Scraping

on:
  schedule:
    - cron: '0 0,12 * * *'  # Run the action every 2 hours
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape_prices:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install  # Install Playwright browser binaries
  
    # Install Xvfb (virtual display for running browsers in non-headless mode)
    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    # Start Xvfb without displaying warnings
    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1280x1024x24 & export DISPLAY=:99 2>/dev/null

    # Run the scraping script
    - name: Run scraping script
      run: |
        python scrape_hotel_prices.py  # Ensure the script name is correct

    # Check if the file exists before sending
    - name: Check file existence
      run: |
        if [ -f daily_price_multiple_hotels.xlsx ]; then
          echo "File exists, proceeding to send via Telegram."
        else
          echo "File not found. Exiting script."
          exit 1
        fi

    # Send the file via Telegram using the script
    - name: Send Excel file via Telegram
      run: |
        python send_telegram.py  # This will send the file via Telegram
      env:
        TELEGRAM_BOT_TOKEN: "7751308203:AAF_5lHsCIfb5Uo2ZM6FVHcnyofJKm1jwdA"  # Replace with your token
        TELEGRAM_CHAT_ID: "-4647316485"    # Replace with your chat ID
