jobs:
  scrape_prices:
    runs-on: ubuntu-latest  # Or use a specific Ubuntu version

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install  # Install Playwright browser binaries
        sudo apt-get install -y xvfb  # Install X virtual framebuffer

    # Run scraping script with xvfb-run
    - name: Run scraping script with Xvfb
      run: |
        xvfb-run -a python scrape_hotel_prices.py  # Run your script using xvfb-run

    # Upload the result (Excel file) as an artifact
    - name: Upload price data
      uses: actions/upload-artifact@v4
      with:
        name: hotel-price-data
        path: daily_price_multiple_hotels.xlsx
